<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="robot_hare_wheel_bot">

  <!-- === CONSTANTS === -->
  <xacro:property name="base_x" value="0.25"/>
  <xacro:property name="base_y" value="0.18"/>
  <xacro:property name="base_z" value="0.35"/>
  <xacro:property name="base_origin_z" value="0.275"/>

  <xacro:property name="head_x" value="0.16"/>
  <xacro:property name="head_y" value="0.14"/>
  <xacro:property name="head_z" value="0.12"/>
  <xacro:property name="head_origin_z" value="0.06"/>

  <xacro:property name="ear_r" value="0.03"/>
  <xacro:property name="ear_l" value="0.12"/>
  <xacro:property name="ear_y" value="0.035"/>
  <xacro:property name="ear_z" value="0.16"/>

  <xacro:property name="arm_x" value="0.05"/>
  <xacro:property name="arm_y" value="0.05"/>
  <xacro:property name="arm_z" value="0.20"/>
  <xacro:property name="arm_y_offset" value="0.09"/>
  <xacro:property name="arm_origin_z" value="0.35"/>

  <xacro:property name="wheel_r" value="0.10"/>
  <xacro:property name="wheel_w" value="0.05"/>
  <xacro:property name="wheel_y_offset" value="0.13"/>
  <xacro:property name="wheel_origin_z" value="0.10"/>

  <!-- === MATERIALS (defined once, referenced everywhere) === -->
  <material name="body_mat"><color rgba="0.6 0.6 0.7 1.0"/></material>
  <material name="head_mat"><color rgba="0.5 0.5 0.6 1.0"/></material>
  <material name="arm_mat"><color rgba="0.5 0.5 0.6 1.0"/></material>
  <material name="ear_mat"><color rgba="1.0 0.9 0.2 1.0"/></material>
  <material name="wheel_mat"><color rgba="0.1 0.1 0.1 1.0"/></material>


  <!-- === BASE LINK === -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 ${base_origin_z}"/>
      <mass value="3.5"/>
      <inertia ixx="0.12" ixy="0" ixz="0"
               iyy="0.12" iyz="0"
               izz="0.15"/>
    </inertial>

    <visual>
      <origin xyz="0 0 ${base_origin_z}"/>
      <geometry><box size="${base_x} ${base_y} ${base_z}"/></geometry>
      <material name="body_mat"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${base_origin_z}"/>
      <geometry><box size="${base_x} ${base_y} ${base_z}"/></geometry>
    </collision>
  </link>


  <!-- === HEAD === -->
  <joint name="head_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="head_link"/>
    <origin xyz="0 0 0.45"/>
  </joint>

  <link name="head_link">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.02" ixy="0" ixz="0"
               iyy="0.02" iyz="0"
               izz="0.02"/>
    </inertial>

    <visual>
      <origin xyz="0 0 ${head_origin_z}"/>
      <geometry><box size="${head_x} ${head_y} ${head_z}"/></geometry>
      <material name="head_mat"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${head_origin_z}"/>
      <geometry><box size="${head_x} ${head_y} ${head_z}"/></geometry>
    </collision>
  </link>


  <!-- === EAR MACRO === -->
  <xacro:macro name="ear" params="name ysign">
    <joint name="${name}_joint" type="fixed">
      <parent link="head_link"/>
      <child  link="${name}"/>
      <origin xyz="0 0 0"/>
    </joint>

    <link name="${name}">
      <!-- добавлено inertial для physical properties -->
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.0002" ixy="0" ixz="0"
                 iyy="0.0002" iyz="0"
                 izz="0.0001"/>
      </inertial>

      <visual>
        <origin xyz="0 ${ysign*ear_y} ${ear_z}"/>
        <geometry><cylinder radius="${ear_r}" length="${ear_l}"/></geometry>
        <material name="ear_mat"/>
      </visual>

      <collision>
        <origin xyz="0 ${ysign*ear_y} ${ear_z}"/>
        <geometry><cylinder radius="${ear_r}" length="${ear_l}"/></geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:ear name="left_ear"  ysign="1"/>
  <xacro:ear name="right_ear" ysign="-1"/>


  <!-- === ARM MACRO === -->
  <xacro:macro name="arm" params="name ysign">
    <joint name="${name}_joint" type="fixed">
      <parent link="base_link"/>
      <child  link="${name}"/>
      <origin xyz="0 0 0"/>
    </joint>

    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.3"/>
        <inertia ixx="0.005" ixy="0" ixz="0"
                 iyy="0.005" iyz="0"
                 izz="0.005"/>
      </inertial>

      <visual>
        <origin xyz="0 ${ysign*arm_y_offset} ${arm_origin_z}"/>
        <geometry><box size="${arm_x} ${arm_y} ${arm_z}"/></geometry>
        <material name="arm_mat"/>
      </visual>

      <collision>
        <origin xyz="0 ${ysign*arm_y_offset} ${arm_origin_z}"/>
        <geometry><box size="${arm_x} ${arm_y} ${arm_z}"/></geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:arm name="left_arm"  ysign="1"/>
  <xacro:arm name="right_arm" ysign="-1"/>


  <!-- === WHEEL MACRO === -->
  <xacro:macro name="wheel" params="side ysign">
    <joint name="${side}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child  link="${side}_wheel_link"/>
      <origin xyz="0 ${ysign*wheel_y_offset} ${wheel_origin_z}"/>
      <axis xyz="0 1 0"/>
    </joint>

    <link name="${side}_wheel_link">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.4"/>
        <inertia ixx="0.008" ixy="0" ixz="0"
                 iyy="0.008" iyz="0"
                 izz="0.008"/>
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_r}" length="${wheel_w}"/></geometry>
        <material name="wheel_mat"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_r}" length="${wheel_w}"/></geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:wheel side="left"  ysign="1"/>
  <xacro:wheel side="right" ysign="-1"/>

</robot>
