<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="robot_hare_wheel_bot">

  <!-- Подключаем gazebo-плагины (diff drive, joint states, материалы) -->
  <xacro:include filename="robot.gazebo.xacro"/>

  <!-- === CONSTANTS === -->
  <xacro:property name="base_x" value="0.25"/>
  <xacro:property name="base_y" value="0.18"/>
  <xacro:property name="base_z" value="0.35"/>

  <!-- 4 small wheels (replaces 2 big wheels) -->
  <xacro:property name="drive_wheel_r" value="0.06"/>
  <xacro:property name="drive_wheel_w" value="0.04"/>

  <!-- wheel positions (front/rear) -->
  <xacro:property name="wheel_x_front" value="0.09"/>
  <xacro:property name="wheel_x_rear"  value="-0.09"/>

  <!-- Put wheels exactly outside the body -->
  <xacro:property name="wheel_y_offset" value="${base_y/2 + drive_wheel_w/2}"/>

  <!-- Make body sit correctly above the wheels -->
  <xacro:property name="base_origin_z" value="${drive_wheel_r + base_z/2}"/>

  <xacro:property name="head_x" value="0.16"/>
  <xacro:property name="head_y" value="0.14"/>
  <xacro:property name="head_z" value="0.12"/>
  <xacro:property name="head_origin_z" value="0.06"/>

  <xacro:property name="ear_r" value="0.03"/>
  <xacro:property name="ear_l" value="0.12"/>
  <xacro:property name="ear_y" value="0.035"/>
  <xacro:property name="ear_z" value="0.16"/>

  <xacro:property name="arm_x" value="0.05"/>
  <xacro:property name="arm_y" value="0.05"/>
  <xacro:property name="arm_z" value="0.20"/>
  <xacro:property name="arm_y_offset" value="0.09"/>
  <!-- arms near the top of the body, like before -->
  <xacro:property name="arm_origin_z" value="${base_origin_z + base_z/2 - arm_z/2}"/>

  <!-- === MATERIALS === -->
  <material name="body_mat"><color rgba="0.6 0.6 0.7 1.0"/></material>
  <material name="head_mat"><color rgba="0.5 0.5 0.6 1.0"/></material>
  <material name="arm_mat"><color rgba="0.5 0.5 0.6 1.0"/></material>
  <material name="ear_mat"><color rgba="1.0 0.9 0.2 1.0"/></material>
  <material name="wheel_mat"><color rgba="0.1 0.1 0.1 1.0"/></material>
  <material name="sensor_mat"><color rgba="0.3 0.3 0.3 1.0"/></material>
  <material name="lidar_mat"><color rgba="1.0 0.0 0.0 1.0"/></material>

  <!-- === BASE LINK === -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 ${base_origin_z}"/>
      <mass value="3.5"/>
      <inertia ixx="0.12" ixy="0" ixz="0"
               iyy="0.12" iyz="0"
               izz="0.15"/>
    </inertial>

    <visual>
      <origin xyz="0 0 ${base_origin_z}"/>
      <geometry><box size="${base_x} ${base_y} ${base_z}"/></geometry>
      <material name="body_mat"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${base_origin_z}"/>
      <geometry><box size="${base_x} ${base_y} ${base_z}"/></geometry>
    </collision>
  </link>

  <!-- === HEAD === -->
  <joint name="head_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="head_link"/>
    <!-- attach head to the top face of the base -->
    <origin xyz="0 0 ${base_origin_z + base_z/2}"/>
  </joint>

  <link name="head_link">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.02" ixy="0" ixz="0"
               iyy="0.02" iyz="0"
               izz="0.02"/>
    </inertial>

    <visual>
      <origin xyz="0 0 ${head_origin_z}"/>
      <geometry><box size="${head_x} ${head_y} ${head_z}"/></geometry>
      <material name="head_mat"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${head_origin_z}"/>
      <geometry><box size="${head_x} ${head_y} ${head_z}"/></geometry>
    </collision>
  </link>

  <!-- === EAR MACRO === -->
  <xacro:macro name="ear" params="name ysign">
    <joint name="${name}_joint" type="fixed">
      <parent link="head_link"/>
      <child  link="${name}"/>
      <origin xyz="0 0 0"/>
    </joint>

    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.0002" ixy="0" ixz="0"
                 iyy="0.0002" iyz="0"
                 izz="0.0001"/>
      </inertial>

      <visual>
        <origin xyz="0 ${ysign*ear_y} ${ear_z}"/>
        <geometry><cylinder radius="${ear_r}" length="${ear_l}"/></geometry>
        <material name="ear_mat"/>
      </visual>

      <collision>
        <origin xyz="0 ${ysign*ear_y} ${ear_z}"/>
        <geometry><cylinder radius="${ear_r}" length="${ear_l}"/></geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:ear name="left_ear"  ysign="1"/>
  <xacro:ear name="right_ear" ysign="-1"/>

  <!-- === ARM MACRO === -->
  <xacro:macro name="arm" params="name ysign">
    <joint name="${name}_joint" type="fixed">
      <parent link="base_link"/>
      <child  link="${name}"/>
      <origin xyz="0 0 0"/>
    </joint>

    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.3"/>
        <inertia ixx="0.005" ixy="0" ixz="0"
                 iyy="0.005" iyz="0"
                 izz="0.005"/>
      </inertial>

      <visual>
        <origin xyz="0 ${ysign*arm_y_offset} ${arm_origin_z}"/>
        <geometry><box size="${arm_x} ${arm_y} ${arm_z}"/></geometry>
        <material name="arm_mat"/>
      </visual>

      <collision>
        <origin xyz="0 ${ysign*arm_y_offset} ${arm_origin_z}"/>
        <geometry><box size="${arm_x} ${arm_y} ${arm_z}"/></geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:arm name="left_arm"  ysign="1"/>
  <xacro:arm name="right_arm" ysign="-1"/>

  <!-- === 4 SMALL WHEELS MACRO === -->
  <xacro:macro name="drive_wheel" params="name x ysign">
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child  link="${name}_link"/>
      <origin xyz="${x} ${ysign*wheel_y_offset} ${drive_wheel_r}"/>
      <axis xyz="0 1 0"/>
    </joint>

    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.25"/>
        <inertia ixx="0.003" ixy="0" ixz="0"
                 iyy="0.003" iyz="0"
                 izz="0.003"/>
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${drive_wheel_r}" length="${drive_wheel_w}"/></geometry>
        <material name="wheel_mat"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${drive_wheel_r}" length="${drive_wheel_w}"/></geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- Front pair -->
  <xacro:drive_wheel name="front_left_wheel"  x="${wheel_x_front}" ysign="1"/>
  <xacro:drive_wheel name="front_right_wheel" x="${wheel_x_front}" ysign="-1"/>

  <!-- Rear pair -->
  <xacro:drive_wheel name="rear_left_wheel"   x="${wheel_x_rear}"  ysign="1"/>
  <xacro:drive_wheel name="rear_right_wheel"  x="${wheel_x_rear}"  ysign="-1"/>

  <!-- ========================================================= -->
  <!-- === SENSORS (same topics as the other robot)            === -->
  <!--     lidar: topic "scan"                                  -->
  <!--     depth camera: topic "depth_camera"                   -->
  <!--     imu: topic "imu"                                     -->
  <!-- ========================================================= -->

  <!-- "roof" height of the base box in base_link coordinates -->
  <xacro:property name="base_top_z" value="${base_origin_z + base_z/2}"/>

  <xacro:property name="lidar_radius" value="0.03"/>
  <xacro:property name="lidar_height" value="0.03"/>
  <xacro:property name="lidar_link_z" value="${base_top_z + lidar_height/2}"/>

  <link name="lidar_link">
    <visual>
      <geometry><cylinder radius="${lidar_radius}" length="${lidar_height}"/></geometry>
      <material name="lidar_mat"/>
    </visual>
    <collision>
      <geometry><cylinder radius="${lidar_radius}" length="${lidar_height}"/></geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="lidar_link"/>
    <origin xyz="0 0 ${lidar_link_z}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="lidar_link">
    <material>Gazebo/Red</material>
    <sensor name="lidar" type="gpu_lidar">
      <pose>0 0 0 0 0 0</pose>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>

      <!-- IMPORTANT: same topic name as your lidar.launch.py bridge -->
      <topic>scan</topic>
      <gz_frame_id>lidar_link</gz_frame_id>

      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.15</min>
          <max>6.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
    </sensor>
  </gazebo>

  <xacro:property name="camera_size" value="0.02"/>
  <xacro:property name="camera_x" value="${base_x/2 + 0.03}"/>
  <xacro:property name="camera_y" value="0.0"/>
  <xacro:property name="camera_z" value="${base_origin_z + 0.10}"/>

  <link name="depth_camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${camera_size} ${camera_size*3} ${camera_size}"/></geometry>
      <material name="sensor_mat"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${camera_size} ${camera_size*3} ${camera_size}"/></geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="depth_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="depth_camera_link"/>
    <origin xyz="${camera_x} ${camera_y} ${camera_z}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="depth_camera_link">
    <sensor name="depth_camera" type="depth_camera">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>6</update_rate>
      <always_on>true</always_on>
      <visualize>true</visualize>

      <!-- IMPORTANT: same topic name as your depth.launch.py bridge -->
      <topic>depth_camera</topic>
      <gz_frame_id>depth_camera_link</gz_frame_id>

      <camera>
        <horizontal_fov>1.51843645</horizontal_fov>
        <image>
          <width>848</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>10</far>
        </clip>
        <lens>
          <intrinsics>
            <fx>421.61578369140625</fx>
            <fy>421.61578369140625</fy>
            <cx>422.2854309082031</cx>
            <cy>236.57237243652344</cy>
            <s>0</s>
          </intrinsics>
        </lens>
        <depth_camera>
          <output>depths</output>
        </depth_camera>
      </camera>
    </sensor>
  </gazebo>

  <xacro:property name="imu_size" value="0.01"/>
  <xacro:property name="imu_x" value="0.0"/>
  <xacro:property name="imu_y" value="0.0"/>
  <xacro:property name="imu_z" value="${base_origin_z}"/>

  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${imu_size} ${imu_size} ${imu_size}"/></geometry>
      <material name="sensor_mat"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${imu_size} ${imu_size} ${imu_size}"/></geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.000001" ixy="0.0" ixz="0.0"
               iyy="0.000001" iyz="0.0"
               izz="0.000001"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="imu_link"/>
    <origin xyz="${imu_x} ${imu_y} ${imu_z}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <pose>0 0 0 0 0 0</pose>
      <always_on>true</always_on>
      <update_rate>50</update_rate>
      <visualize>true</visualize>
      <imu>
        <angular_velocity>
          <x><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></x>
          <y><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></y>
          <z><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></z>
        </angular_velocity>
        <linear_acceleration>
          <x><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></x>
          <y><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></y>
          <z><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></z>
        </linear_acceleration>
      </imu>

      <!-- IMPORTANT: same topic name as your imu.launch.py bridge -->
      <topic>imu</topic>
    </sensor>
  </gazebo>

</robot>
